Fix `Use` bool array issue caused by pandas 3.0
For the latest pandas, the following error started appearing from
reading the CSV log file:

```python
TypeError: Invalid value 'True' for dtype 'int64'
```

This is because in pandas 3.0, we can't change the type of the `Use`
array after loading (which was either `int64` or `str`), and we have
to instead create a new array that will replace it.

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>